name: ci

on:
  push:
    branches: master

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: gherkintw
          password: 545b13b6-5c73-4c26-8039-ec1511f0f3d6